export type SelectableClass = {
  name: string;
};

export const selectableClasses: SelectableClass[] = [
  { name: 'Ace of Cards' },
  { name: 'Arcanist' },
  { name: 'Chanter' },
  { name: 'Chimerist' },
  { name: 'Commander' },
  { name: 'Dancer' },
  { name: 'Darkblade' },
  { name: 'Elementalist' },
  { name: 'Entropist' },
  { name: 'Esper' },
  { name: 'Floralist' },
  { name: 'Fury' },
  { name: 'Gourmet' },
  { name: 'Guardian' },
  { name: 'Hunter' },
  { name: 'Illusionist' },
  { name: 'Invoker' },
  { name: 'Loremaster' },
  { name: 'Merchant' },
  { name: 'Monk' },
  { name: 'Mutant' },
  { name: 'Necromancer' },
  { name: 'Orator' },
  { name: 'Pilot' },
  { name: 'Rogue' },
  { name: 'Sharpshooter' },
  { name: 'Spiritist' },
  { name: 'Symbolist' },
  { name: 'Tinkerer' },
  { name: 'Wayfarer' },
  { name: 'Weaponmaster' },
  { name: 'Hexer' },
  { name: 'Slayer' },
  { name: 'Tamer' },
];
